import uuid
from sqlalchemy import Column, String, Boolean, Integer
from sqlalchemy.dialects.postgresql import JSONB, UUID
from libs.database import Base


class Transportexchangegroup(Base):
    __tablename__ = 'Transportexchangegroup'
    
    id = Column(UUID, primary_key=True, default=uuid.uuid4, index=True)
    Job_Number = Column(Integer, unique=True, index=True)
    Account_Code = Column(String)
    Customer_Name = Column(String)
    Job_Type = Column(String)
    Del_Type = Column(String)
    Work_Type = Column(String)
    OrderNo = Column(String)
    Ref2 = Column(String)
    Ref3 = Column(String)
    Goods = Column(String)
    Quantity = Column(String)
    Weight = Column(String)
    Distance = Column(String)
    Volume = Column(String)
    Collection_Add_1 = Column(String)
    Collection_Add_2 = Column(String)
    Collection_Add_3 = Column(String)
    Collection_Add_4 = Column(String)
    Collection_Add_5 = Column(String)
    Collection_PostCode = Column(String)
    Collection_Date = Column(String)
    Collection_Time = Column(String)
    Delivery_Add_1 = Column(String)
    Delivery_Add_2 = Column(String)
    Delivery_Add_3 = Column(String)
    Delivery_Add_4 = Column(String)
    Delivery_Add_5 = Column(String)
    Delivery_PostCode = Column(String)
    Delivery_Date = Column(String)
    Delivery_Time = Column(String)
    Notes = Column(String)
    Instructions = Column(String)
    Job_Rate = Column(String)
    ColZone = Column(String)
    DelZone = Column(String)
    
    freightType = Column(String)
    jobDescription = Column(String)
    minVehicleSize = Column(String)
    phoneNumber = Column(String)
    quotesEnabled = Column(Boolean)
    podHardCopiesRequired = Column(Boolean)
    bodyType = Column(String)
    _from = Column(JSONB)
    to = Column(JSONB)
    customerReference = Column(String)
    commodity = Column(String)
    grossWeight = Column(JSONB)
    readyAt = Column(String)
    collectBy = Column(String)
    deliverFrom = Column(String)
    deliverBy = Column(String)
    
    orderId = Column(String)